# Generated by Django 5.1 on 2024-09-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_images_patients_doctors_image_doctors_profecion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reports",
            name="baloon_presure",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
