# Generated by Django 5.1.2 on 2024-10-12 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image_patient_doctor_report_delete_doctors'),
        ('api', '0003_reports_baloon_presure'),
    ]

    operations = [
    ]
