# Generated by Django 5.0.4 on 2024-10-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_doctors_remove_doctor_username_delete_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patients",
            name="hospital_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="patients",
            name="national_id",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
