# Generated by Django 5.1 on 2024-09-15 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hos_id", models.CharField(max_length=10)),
                ("date", models.DateField(null=True)),
                ("report_imgs", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("national_id", models.CharField(max_length=20)),
                ("hospital_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("birth", models.DateField()),
                ("address", models.CharField(max_length=150)),
                ("contact", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="doctors",
            name="image",
            field=models.ImageField(
                blank=True,
                default="profile_pics/user.jpg",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
        migrations.AddField(
            model_name="doctors",
            name="profecion",
            field=models.CharField(default="other", max_length=100),
        ),
        migrations.AlterField(
            model_name="doctors",
            name="username",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="docs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Reports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("Indication", models.CharField(max_length=150)),
                ("BHT", models.CharField(max_length=150)),
                ("oparators", models.CharField(max_length=200)),
                ("Vascular_Access", models.CharField(max_length=250)),
                ("Catheters", models.CharField(max_length=150)),
                ("catheter_type", models.CharField(max_length=300, null=True)),
                ("discription", models.TextField(null=True)),
                ("baloon_size", models.CharField(max_length=150, null=True)),
                ("stent_name", models.CharField(max_length=150, null=True)),
                ("stent_pressure", models.CharField(max_length=150, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="api.patients",
                    ),
                ),
            ],
        ),
    ]
