# Generated by Django 5.0.4 on 2024-09-17 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reports_baloon_presure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='person',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='hos_id',
            new_name='hospital_id',
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='profile_pics/user.jpg', null=True, upload_to='profile_pics/')),
                ('name', models.CharField(max_length=150)),
                ('profession', models.CharField(default='other', max_length=100)),
                ('birth', models.DateField()),
                ('contact', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('speciality', models.CharField(blank=True, max_length=150, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('indication', models.CharField(max_length=150)),
                ('BHT', models.CharField(max_length=150)),
                ('operators', models.CharField(max_length=200)),
                ('vascular_access', models.CharField(max_length=250)),
                ('catheters', models.CharField(max_length=150)),
                ('catheter_type', models.CharField(max_length=300, null=True)),
                ('description', models.TextField(null=True)),
                ('balloon_size', models.CharField(max_length=150, null=True)),
                ('balloon_pressure', models.CharField(max_length=150, null=True)),
                ('stent_name', models.CharField(max_length=150, null=True)),
                ('stent_pressure', models.CharField(max_length=150, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
